# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "dwc3_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/dc4c4fad-614c-44d5-95b8-56d0307cc5fa";
    fsType = "ext4";
  };

  fileSystems."/nix"= {
    device = "/dev/disk/by-uuid/35e48f86-290c-43f3-9567-f677f2f98a4e";
    fsType = "ext4";
  };

  # 外部ストレージを使用するので
  systemd.services.nix-daemon = {
    after = [ "nix.mount" ];                   # nix.mount後に起動
    requires = [ "nix.mount" ];                # nix.mountを依存関係に追加
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C66B-7BC1";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/ad09652b-13f2-455f-8614-1488908f71dd"; }];
  boot.resumeDevice = "/dev/disk/by-uuid/ad09652b-13f2-455f-8614-1488908f71dd";

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
