-- Generated by dev/rustowl.nix; before the first switch the bridge may be absent.
local bridge = vim.fn.stdpath('data') .. '/nix/rustowl.lua'
local rustowl = vim.fn.filereadable(bridge) == 1 and dofile(bridge) or nil

local plugins = {
  {
    'mrcjkb/rustaceanvim',
    version = '^5',
    lazy = false,
    dependencies = { "mfussenegger/nvim-dap" },
    init = function()
      -- 生成元: modules/home-manager/dev/neovim/default.nix
      local codelldb_path = dofile(vim.fn.stdpath("data") .. "/nix/codelldb-path.lua")
      local suffix = vim.fn.has('macunix') == 1 and 'dylib' or 'so'
      local liblldb_path = vim.fn.fnamemodify(codelldb_path, ':h:h') .. '/lldb/lib/liblldb.' .. suffix

      vim.g.rustaceanvim = {
        dap = {
          adapter = require('rustaceanvim.config').get_codelldb_adapter(codelldb_path, liblldb_path),
        },
      }
    end,
  },
}

if rustowl then
  plugins[#plugins + 1] = {
    name = 'rustowl',
    dir = rustowl.plugin,
    ft = 'rust',
    opts = {
      client = { cmd = { rustowl.command } },
      auto_attach = true,
      auto_enable = false,
      idle_time = 500,
    },
    keys = {
      { '<leader>lo', '<cmd>Rustowl toggle<cr>', desc = 'RustOwl toggle' },
    },
    config = function(_, opts)
      require('rustowl').setup(opts)
      require('plugins.lang.rustowl-hover').setup()
    end,
  }
end

return plugins
