-- wezterm configuration
-- Default keybindings: https://wezterm.org/config/default-keys.html
-- Key tables: https://wezterm.org/config/key-tables.html
local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()

-- Shell
config.default_prog = { 'nu' }
config.mux_enable_ssh_agent = false
config.enable_wayland = false

-- IME
config.use_ime = true

-- Tab bar
config.hide_tab_bar_if_only_one_tab = true
config.tab_bar_at_bottom = true
config.show_new_tab_button_in_tab_bar = false
config.show_tab_index_in_tab_bar = false
config.window_background_gradient = { colors = { '#000000' } }
config.colors = { tab_bar = { inactive_tab_edge = 'none' } }

-- Font (font.lua is generated by Nix - see modules/home-manager/gui.nix)
config.font_size = 15.0
config.font = wezterm.font(dofile(wezterm.config_dir .. '/font.lua'))

-- Opacity
local DEFAULT_OPACITY = 0.75
config.window_background_opacity = DEFAULT_OPACITY

local function change_opacity(delta)
  return wezterm.action_callback(function(win, _pane)
    local overrides = win:get_config_overrides() or {}
    local current = overrides.window_background_opacity or DEFAULT_OPACITY
    overrides.window_background_opacity = math.max(0.0, math.min(1.0, current + delta))
    win:set_config_overrides(overrides)
  end)
end

local function reset_opacity()
  return wezterm.action_callback(function(win, _pane)
    local overrides = win:get_config_overrides() or {}
    overrides.window_background_opacity = DEFAULT_OPACITY
    win:set_config_overrides(overrides)
  end)
end

-- Leader key (tmux-style prefix)
config.leader = { key = 's', mods = 'CTRL', timeout_milliseconds = 2000 }

-- Keybindings
-- Default keybindings are preserved unless explicitly overridden below.
-- Reference: https://wezterm.org/config/default-keys.html
--
-- Notable defaults available without configuration:
--   Copy:            Ctrl+Shift+C
--   Paste:           Ctrl+Shift+V
--   New tab:         Ctrl+Shift+T
--   Close tab:       Ctrl+Shift+W
--   Next/Prev tab:   Ctrl+Tab / Ctrl+Shift+Tab
--   Tab by number:   Ctrl+Shift+1~9
--   Split vertical:  Ctrl+Shift+Alt+"
--   Split horizontal:Ctrl+Shift+Alt+%
--   Pane navigate:   Ctrl+Shift+Arrow
--   Pane resize:     Ctrl+Shift+Alt+Arrow
--   Pane zoom:       Ctrl+Shift+Z
--   Copy mode:       Ctrl+Shift+X
--   Search:          Ctrl+Shift+F
--   Command palette: Ctrl+Shift+P
--   Fullscreen:      Alt+Enter
--   Font size +/-:   Ctrl+= / Ctrl+-  (overridden below for opacity)
--   Font size reset: Ctrl+0           (overridden below for opacity)
config.keys = {
  -- [Override] Ctrl+=/-/0: opacity instead of default font size
  -- Font size is handled by Ctrl+MouseWheel instead (see mouse_bindings)
  { key = '=', mods = 'CTRL', action = change_opacity(0.05) },
  { key = '-', mods = 'CTRL', action = change_opacity(-0.05) },
  { key = '0', mods = 'CTRL', action = reset_opacity() },

  -- Fullscreen (addition to default Alt+Enter)
  { key = 'F11', action = act.ToggleFullScreen },

  -- Leader: shell line editing
  { key = '0', mods = 'LEADER', action = act.SendKey { key = 'a', mods = 'CTRL' } },
  { key = 'A', mods = 'LEADER', action = act.SendKey { key = 'e', mods = 'CTRL' } },
  { key = 'd', mods = 'LEADER', action = act.SendKey { key = 'u', mods = 'CTRL' } },
  { key = 'w', mods = 'LEADER', action = act.SendKey { key = 'f', mods = 'META' } },

  -- Leader: workspace
  { key = 'W', mods = 'LEADER', action = act.ShowLauncherArgs { flags = 'WORKSPACES', title = 'Select workspace' } },
  {
    key = 'R',
    mods = 'LEADER',
    action = act.PromptInputLine {
      description = '(wezterm) Set workspace title:',
      action = wezterm.action_callback(function(_win, _pane, line)
        if line then
          wezterm.mux.rename_workspace(wezterm.mux.get_active_workspace(), line)
        end
      end),
    },
  },

  -- Leader: pane
  { key = 's', mods = 'LEADER', action = act.SplitVertical { domain = 'CurrentPaneDomain' } },
  { key = 'v', mods = 'LEADER', action = act.SplitHorizontal { domain = 'CurrentPaneDomain' } },
  { key = 'q', mods = 'LEADER', action = act.ActivateKeyTable { name = 'resize_pane', one_shot = false } },
  { key = 'e', mods = 'LEADER', action = act.RotatePanes 'Clockwise' },
  { key = 'E', mods = 'LEADER', action = act.RotatePanes 'CounterClockwise' },
  { key = 'h', mods = 'LEADER', action = act.ActivatePaneDirection 'Left' },
  { key = 'j', mods = 'LEADER', action = act.ActivatePaneDirection 'Down' },
  { key = 'k', mods = 'LEADER', action = act.ActivatePaneDirection 'Up' },
  { key = 'l', mods = 'LEADER', action = act.ActivatePaneDirection 'Right' },
  { key = 'x', mods = 'LEADER', action = act.CloseCurrentPane { confirm = true } },
  { key = 'X', mods = 'LEADER', action = act.CloseCurrentTab { confirm = true } },

  -- Leader: tab
  { key = 'c', mods = 'LEADER', action = act { SpawnTab = 'CurrentPaneDomain' } },
  { key = 'n', mods = 'LEADER', action = act { ActivateTabRelative = 1 } },
  { key = 'N', mods = 'LEADER', action = act { ActivateTabRelative = -1 } },

  -- Leader: copy mode (addition to default Ctrl+Shift+X)
  { key = 'y', mods = 'LEADER', action = act.ActivateCopyMode },
}

-- Mouse bindings (font size via Ctrl+Wheel since Ctrl+=/-/0 is used for opacity)
config.mouse_bindings = {
  { event = { Down = { streak = 1, button = { WheelUp = 1 } } }, mods = 'CTRL', action = act.IncreaseFontSize },
  { event = { Down = { streak = 1, button = { WheelDown = 1 } } }, mods = 'CTRL', action = act.DecreaseFontSize },
}

-- Key tables
-- copy_mode: extend defaults with QuickSelect
-- Reference: https://wezterm.org/config/lua/wezterm.gui/default_key_tables.html
local copy_mode = wezterm.gui.default_key_tables().copy_mode
table.insert(copy_mode, { key = 'q', mods = 'NONE', action = act.QuickSelect })

config.key_tables = {
  copy_mode = copy_mode,
  resize_pane = {
    { key = 'LeftArrow', action = act.AdjustPaneSize { 'Left', 1 } },
    { key = 'h',         action = act.AdjustPaneSize { 'Left', 3 } },
    { key = 'RightArrow', action = act.AdjustPaneSize { 'Right', 1 } },
    { key = 'l',          action = act.AdjustPaneSize { 'Right', 3 } },
    { key = 'UpArrow',   action = act.AdjustPaneSize { 'Up', 1 } },
    { key = 'k',         action = act.AdjustPaneSize { 'Up', 3 } },
    { key = 'DownArrow', action = act.AdjustPaneSize { 'Down', 1 } },
    { key = 'j',         action = act.AdjustPaneSize { 'Down', 3 } },
    { key = 'Escape',    action = 'PopKeyTable' },
  },
}

return config
